### ISSUE TITLE
Run Seal5 "demo.sh" Error

### ISSUE THREAD

**Issue by dingzex** [tum-ei-eda/seal5#108]
INFO - Traceback (most recent call last):
INFO -   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
INFO -     return _run_code(code, main_globals, None,
INFO -   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
INFO -     exec(code, run_globals)
INFO -   File "/mnt/d/Seal5/seal5/seal5/frontends/coredsl2_seal5/parser.py", line 329, in <module>
INFO -     main()
INFO -   File "/mnt/d/Seal5/seal5/seal5/frontends/coredsl2_seal5/parser.py", line 296, in main
INFO -     op = behav_builder.visit(instr_def.operation)
INFO -   File "/home/ding/.local/lib/python3.8/site-packages/antlr4/tree/Tree.py", line 34, in visit
INFO -     return tree.accept(self)
INFO - AttributeError: 'str' object has no attribute 'accept'
.........
Traceback (most recent call last):
  File "/home/ding/.local/bin/seal5", line 33, in <module>
    sys.exit(load_entry_point('seal5', 'console_scripts', 'seal5')())
  File "/mnt/d/Seal5/seal5/seal5/cli/main.py", line 61, in main
    args.func(args)
  File "/mnt/d/Seal5/seal5/seal5/cli/load.py", line 59, in handle
    seal5_flow.load(files=list(args.files), overwrite=args.overwrite, verbose=args.verbose)
  File "/mnt/d/Seal5/seal5/seal5/flow.py", line 405, in load
    self.load_cdsl(file, verbose=verbose, overwrite=overwrite)
  File "/mnt/d/Seal5/seal5/seal5/flow.py", line 386, in load_cdsl
    self.parse_coredsl(file, dest, verbose=verbose)
  File "/mnt/d/Seal5/seal5/seal5/flow.py", line 366, in parse_coredsl
    utils.python(
  File "/mnt/d/Seal5/seal5/seal5/utils.py", line 175, in python
    return exec_getout(sys.executable, *args, **kwargs)
  File "/mnt/d/Seal5/seal5/seal5/utils.py", line 110, in exec_getout
    assert exit_code == 0, "The process returned an non-zero exit code {}! (CMD: `{}`)".format(
AssertionError: The process returned an non-zero exit code 1! (CMD: `/usr/bin/python3 -m seal5.frontends.coredsl2_seal5.parser examples/cdsl/rv_example/Example.core_desc -o /tmp/var/seal5/.seal5/models`)

**Comment by PhilippvK** [comment]
@dingzex Sorry for not answering in time. I am pretty sure that this issues was already fixed a few day after you have posted this. Please make sure to pull the latest changes and re-open this issue in case there are still issues.
